title: Ismael-Moreira-Kt
email: ismaelmoreira363@gmail.com
description: "Ismael-Moreira-Kt Blog"
baseurl: "/Ismael-Moreira-Kt-Blog"
url: "https://ismael-moreira-kt.github.io/Ismael-Moreira-Kt-Blog/"
twitter_username: IsmaelM_Kt
github_username: Ismael-Moreira-Kt

theme: minima
plugins:
  - jekyll-feed

defaults:
  scope: 
    path: "posts"
  values:
    layout: "post"
    author: "Ismael-Moreira-Kt"